### PR TITLE
NMA-1504 : Request Username | Request Details

### PR DESCRIPTION
**Pull request by hadia**
## Issue being fixed or feature implemented

As a user who has submitted a username request, I would like to see all of the information about that request.

- The start and end of the voting period should be shown
- The requested username should be shown
- Any verification info that was submitted should be shown
- The identity should be shown
- The current voting status should be shown 
- The user should be able to be directed to the voting details page if they click on voting status

The user should be able to be directed to the verify Identity screen

## How Has This Been Tested?

- [ ] QA (Mobile Team)

## Checklist:

- [ ] I have performed a self-review of my own code and added comments where necessary
- [ ] I have added or updated relevant unit/integration/functional/e2e tests

### CODE REVIEW

**Review by Syn-McJ — APPROVED** [review]
LGTM

**Review by HashEngineering — APPROVED** [review]
Excellent work.

**Review by HashEngineering — CHANGES_REQUESTED** [review]
`de/schildbach/wallet/ui/username/voting/VotingRequestDetailsFragment.kt: (89, 44): Unresolved reference: cant_open`

CI is reporting the above.

**Comment by hadia** [comment]
> `de/schildbach/wallet/ui/username/voting/VotingRequestDetailsFragment.kt: (89, 44): Unresolved reference: cant_open`
> 
> CI is reporting the above.

Fixed

**Review by HashEngineering — APPROVED** [review]
Excellent

**Pull request merged**
